services:
    mailpit:
        image: axllent/mailpit
        hostname: kosev-mailpit
        container_name: kosev-mailpit
        restart: unless-stopped        
        ports:
            - 8025:8025
            - 1025:1025
        environment:
            MP_MAX_MESSAGES: 5000
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
    redis:
        image: redis:alpine
        hostname: kosev-redis
        container_name: kosev-redis
        restart: unless-stopped
        ports:
            - 6379:6379
        command: redis-server --appendonly yes
